### ISSUE TITLE
mfcr.csv - některé domény jsou duplicitně

### ISSUE THREAD

**Issue by BlueLama** [analogic/cz-gov-blocks#3]
mfcr.csv - některé domény jsou duplicitně, problém je již v datovém souboru mfcr. Nebylo by vhodné duplicity odstranit? Popřípadě vytvořit i seznam all.csv se seznamem všech blokovaných webů a u něj vyřadit duplicity?
Díky.

**Comment by BlueLama** [comment]
Duplicita přetrvává, 2x je např. alfcasino.com

**Comment by analogic** [comment]
ah, kdo by to byl řekl, že k uniq je použití sortu takřka required

**Comment by BlueLama** [comment]
Paráda. Díky moc.
