### ISSUE TITLE
Změna datového formátu souboru u mfcr

### ISSUE THREAD

**Issue by BlueLama** [analogic/cz-gov-blocks#5]
Csv i pdf soubor má odlišný formát, nové sloupce i pořadí údajů.
Půjdou skripty aktualizovat?
Díky za podporu.

**Comment by analogic** [comment]
Určitě - bohužel z nějakého ne úplně zřejmého důvodu zablokoval web MFČR IP adresy githubu, tak to zkouším řešit. Až se to podaří tak opravím i tenhle bug
